--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/XeLiuS/Downloads/1325118.png"

-- Special
background="#08090C"
foreground="#dfdad2"
cursor="#dfdad2"

-- Colors
color0="#08090C"
color1="#797065"
color2="#85796A"
color3="#7F827D"
color4="#958876"
color5="#AFA392"
color6="#C5BAA8"
color7="#dfdad2"
color8="#9c9893"
color9="#797065"
color10="#85796A"
color11="#7F827D"
color12="#958876"
color13="#AFA392"
color14="#C5BAA8"
color15="#dfdad2"
