foreground   #dfdad2
background   #413D38
cursor       #797065

color0       #08090C
color8       #9c9893
color1       #dfdad2
color9       #797065
color2       #dfdad2
color10      #85796A
color3       #7F827D
color11      #7F827D
color4       #dfdad2
color12      #958876
color5       #AFA392
color13      #AFA392
color6       #C5BAA8
color14      #C5BAA8
color7       #dfdad2
color15      #dfdad2
