# Shell variables
# Generated by 'wal'
wallpaper='/home/XeLiuS/Downloads/1325118.png'

# Special
background='#08090C'
foreground='#dfdad2'
cursor='#dfdad2'

# Colors
color0='#08090C'
color1='#797065'
color2='#85796A'
color3='#7F827D'
color4='#958876'
color5='#AFA392'
color6='#C5BAA8'
color7='#dfdad2'
color8='#9c9893'
color9='#797065'
color10='#85796A'
color11='#7F827D'
color12='#958876'
color13='#AFA392'
color14='#C5BAA8'
color15='#dfdad2'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
