--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/xelius/Suckless/Wallpaper/gargantua-black-3840x2160-9621.jpg"

-- Special
background="#0a0b0d"
foreground="#decfc5"
cursor="#decfc5"

-- Colors
color0="#0a0b0d"
color1="#62524F"
color2="#96533C"
color3="#976E5E"
color4="#B58A74"
color5="#7A8088"
color6="#BEA99F"
color7="#decfc5"
color8="#9b9089"
color9="#62524F"
color10="#96533C"
color11="#976E5E"
color12="#B58A74"
color13="#7A8088"
color14="#BEA99F"
color15="#decfc5"
