# Shell variables
# Generated by 'wal'
wallpaper='/home/xelius/Suckless/Wallpaper/gargantua-black-3840x2160-9621.jpg'

# Special
background='#0a0b0d'
foreground='#decfc5'
cursor='#decfc5'

# Colors
color0='#0a0b0d'
color1='#62524F'
color2='#96533C'
color3='#976E5E'
color4='#B58A74'
color5='#7A8088'
color6='#BEA99F'
color7='#decfc5'
color8='#9b9089'
color9='#62524F'
color10='#96533C'
color11='#976E5E'
color12='#B58A74'
color13='#7A8088'
color14='#BEA99F'
color15='#decfc5'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
