# ~/.config/hypr/conf/colors.conf
# ==============================================================================
# STATIC COLORS (Extracted from colors-kitty.conf)
# ==============================================================================

$foreground = rgb(dfdad2)
$background = rgb(413D38)
$cursor     = rgb(797065)

$color0  = rgb(08090C)
$color1  = rgb(dfdad2)
$color2  = rgb(dfdad2)
$color3  = rgb(7F827D)
$color4  = rgb(dfdad2)
$color5  = rgb(AFA392)
$color6  = rgb(C5BAA8)
$color7  = rgb(dfdad2)
$color8  = rgb(9c9893)
$color9  = rgb(797065)
$color10 = rgb(85796A)
$color11 = rgb(7F827D)
$color12 = rgb(958876)
$color13 = rgb(AFA392)
$color14 = rgb(C5BAA8)
$color15 = rgb(dfdad2)

# Your original specific border colors from hyprland.conf
$active_border   = rgba(F5D1A4ee)
$inactive_border = rgba(170E03ee)
$shadow_color    = rgba(F5D1A4ee)
